### ISSUE TITLE
Ignore Cilium Resources in Argo Lab

### ISSUE THREAD

**Issue by g1raffi** [acend/argocd-basics-training#239]
Ignore resources created from Cilium:

```
apiVersion: cilium.io/v2
kind: CiliumIdentity
``` 

Probably best to ignore this custom resource type.

**Comment by g1raffi** [comment]
kubectl -n argocd edit cm argocd-cm

```
data: |
...
  resource.exclusions: |
    - kinds:
      - CiliumIdenty
...
```

**Comment by phil-pona** [comment]
Fixed with https://github.com/acend/terraform-k8s-cluster-lab/pull/145/files#diff-2486a8d3218779f0a491d41ef5e9ca9112286c04be1bbfbf5d2b13477748977d
